name: Build and Deploy Angular App to S3

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      # Install dependencies and build the engine in src/engine
      - name: Install dependencies for engine and build
        working-directory: src/engine
        run: |
          npm install
          npm run build:all

      # Install dependencies and build the Angular project in src/frontend/engine-ui
      - name: Install dependencies and build Angular app
        working-directory: src/frontend/engine-ui
        run: |
          npm install
          npm run build

      # Deploy to S3
      - name: Deploy to S3
        run: aws s3 sync ./src/frontend/engine-ui/dist/engine-ui/ s3://my-angular-app --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
