name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment with caching
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: src/frontend/engine-ui/package-lock.json

      # Install dependencies and build the engine in src/engine
      - name: Install dependencies for engine and build
        working-directory: src/engine
        run: |
          npm ci
          echo "Building engine..."
          npm run build
          echo "Engine build completed!"

      # Install dependencies and build the Angular project in src/frontend/engine-ui
      - name: Install dependencies and build Angular app
        working-directory: src/frontend/engine-ui
        run: |
          npm ci
          npm run build --prod

      # Verify AWS Credentials
      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      # Deploy Frontend to S3
      - name: Deploy Frontend to S3
        run: aws s3 sync ./src/frontend/engine-ui/dist/engine-ui/browser s3://engine-ui-app --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

  build-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment with caching
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: src/backend/backend-service/package-lock.json

      # Install dependencies and build the backend
      - name: Install dependencies and build backend
        working-directory: src/backend/backend-service
        run: |
          npm ci
          npm run build:lambda

      # Verify AWS Credentials
      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      # Deploy backend using AWS CDK
      - name: Deploy backend with CDK
        working-directory: src/backend/backend-service/cdk
        run: |
          npm ci
          npx cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
